version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: temperature-monitor-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb+srv://<username>:<password>@temperaturedb.ad8ez.mongodb.net/?retryWrites=true&w=majority&appName=temperaturedb
      ORIGIN: "*"
      PORT: 5000
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data:
